[package]
org = "ballerinax"
name = "mysql.cdc.driver"
version = "@toml.version@"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mysql.cdc.driver"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.debezium"
artifactId = "debezium-connector-mysql"
version = "@debezium.version@"
path = "./lib/debezium-connector-mysql-@debezium.version@.jar"

[[platform.java21.dependency]]
groupId = "io.debezium"
artifactId = "debezium-connector-binlog"
version = "@debezium.version@"
path = "./lib/debezium-connector-binlog-@debezium.version@.jar"

[[platform.java21.dependency]]
groupId = "io.debezium"
artifactId = "debezium-ddl-parser"
version = "@debezium.version@"
path = "./lib/debezium-ddl-parser-@debezium.version@.jar"

[[platform.java21.dependency]]
groupId = "io.debezium"
artifactId = "mysql-binlog-connector-java"
version = "@debezium.mysql.binlog.version@"
path = "./lib/mysql-binlog-connector-java-@debezium.mysql.binlog.version@.jar"

[[platform.java21.dependency]]
groupId = "org.antlr"
artifactId = "antlr4-runtime"
version = "@antlr.version@"
path = "./lib/antlr4-runtime-@antlr.version@.jar"
